package com.konoplastiy.kanap.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "TransactionInfo")
public class Transaction {

    @DynamoDBHashKey(attributeName = "transaction_id")
    @DynamoDBAutoGeneratedKey
    private String transactionId;

    @DynamoDBAttribute(attributeName = "transaction_type")
    private String transactionType;

    @DynamoDBAttribute(attributeName = "currency")
    private String currency;

    @DynamoDBAttribute(attributeName = "status")
    private String status;
}
