services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.2.0
    environment:
      - SERVICES=dynamodb
      - DEBUG=${LEDGER_LOCALSTACK_DEBUG:-0}
      - AWS_ACCESS_KEY_ID=fake-access-key
      - AWS_SECRET_ACCESS_KEY=fake-secret-key
      - AWS_DEFAULT_REGION=us-west-2
    ports:
      - "4566:4566"
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./scripts/init-ddb.sh:/tmp/localstack/init-ddb.sh
networks:
  kanap-network:
    driver: bridge