services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.2.0
    environment:
      - SERVICES=dynamodb
      - DEBUG=${DEBUG_LOCALSTACK:-0} # Sets DEBUG to DEBUG_LOCALSTACK's value or to 0 if DEBUG_LOCALSTACK is unset or null
      - AWS_ACCESS_KEY_ID=fake-secret-key
      - AWS_SECRET_ACCESS_KEY=fake-secret-key
      - AWS_DEFAULT_REGION=us-west-2
    ports:
      - "4566:4566"
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./scripts/init-ddb.sh:/tmp/localstack/init-ddb.sh

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - kanap-network
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - kanap-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/datasources

networks:
  kanap-network:
    driver: bridge