# Server settings
server:
  port: 8080

# Spring settings
spring:
  application:
    name: kanap
  cloud:
    aws:
      credentials:
        access-key: "fake-access-key"
        secret-key: "fake-secret-key"

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,beans
  statsd:
    metrics:
      export:
        enabled: false

# Project settings
kanap:
  aws:
    endpoint: http://localhost:4566
    region: us-west-2
