# Server settings
server:
  port: 8080

# Spring settings
spring:
  application:
    name: kanap
  cloud:
    aws:
      credentials:
        access-key: "fake-access-key"
        secret-key: "fake-secret-key"

# Project settings
kanap:
  aws:
    endpoint: http://localhost:4566
    region: us-west-2
